### PR TITLE
 Add support for IntelliJ 2022.3.1+

### PR DESCRIPTION
**Pull request by zty5678**
* Add Support for IntelliJ 2022.3.1, 2022.3.2

    * Bump version to 0.0.7

### CODE REVIEW

**Comment by KaustubhPatange** [comment]
Hey @zty5678,

Thanks for this PR, apparently the CI pipeline for this build failed which means it did not generate the plugin zip which I can upload on Jetbrains with this feature request.

Can you take a look at what actually failed?

**Comment by zty5678** [comment]
OK I have made some fix, please try again

**Comment by KaustubhPatange** [comment]
Well is passed the build phase, but failed in verification. Seems like the IntelliJ plugin version is outdated, can you take a look?

**Comment by zty5678** [comment]
According to https://plugins.gradle.org/plugin/org.jetbrains.intellij,  ```id("org.jetbrains.intellij") version "1.12.0"``` is already the newest version.

https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#usage  says that it may need jdk 11 or jdk17.  So maybe we should upgrade the jdk version that CI is using.

**Comment by zty5678** [comment]
I change JAVA_HOME to 1.8 on my own PC, and get the same error:
image

The error disappears after I change  JAVA_HOME  to java 11. So I believe it need java 11 at least.

**Comment by zty5678** [comment]
Ok I change the java-version to 11 in build.yml. Please try again

**Comment by KaustubhPatange** [comment]
Looks good, I'll merge & update the plugin on JetBrains. Thanks for the PR :)

**Pull request merged**
